//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from fsh-processor/antlr/FSH.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace fsh_processor.antlr {
// Disable the warning for CLSCompliant
#pragma warning disable 3021


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IFSHListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class FSHBaseListener : IFSHListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.doc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDoc([NotNull] FSHParser.DocContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.doc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDoc([NotNull] FSHParser.DocContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.entity"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntity([NotNull] FSHParser.EntityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.entity"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntity([NotNull] FSHParser.EntityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.alias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAlias([NotNull] FSHParser.AliasContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.alias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAlias([NotNull] FSHParser.AliasContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.profile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProfile([NotNull] FSHParser.ProfileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.profile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProfile([NotNull] FSHParser.ProfileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.extension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExtension([NotNull] FSHParser.ExtensionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.extension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExtension([NotNull] FSHParser.ExtensionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.logical"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogical([NotNull] FSHParser.LogicalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.logical"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogical([NotNull] FSHParser.LogicalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.resource"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterResource([NotNull] FSHParser.ResourceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.resource"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitResource([NotNull] FSHParser.ResourceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.sdMetadata"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSdMetadata([NotNull] FSHParser.SdMetadataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.sdMetadata"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSdMetadata([NotNull] FSHParser.SdMetadataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.sdRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSdRule([NotNull] FSHParser.SdRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.sdRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSdRule([NotNull] FSHParser.SdRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.lrRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLrRule([NotNull] FSHParser.LrRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.lrRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLrRule([NotNull] FSHParser.LrRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.instance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstance([NotNull] FSHParser.InstanceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.instance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstance([NotNull] FSHParser.InstanceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.instanceMetadata"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstanceMetadata([NotNull] FSHParser.InstanceMetadataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.instanceMetadata"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstanceMetadata([NotNull] FSHParser.InstanceMetadataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.instanceRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstanceRule([NotNull] FSHParser.InstanceRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.instanceRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstanceRule([NotNull] FSHParser.InstanceRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.invariant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInvariant([NotNull] FSHParser.InvariantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.invariant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInvariant([NotNull] FSHParser.InvariantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.invariantMetadata"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInvariantMetadata([NotNull] FSHParser.InvariantMetadataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.invariantMetadata"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInvariantMetadata([NotNull] FSHParser.InvariantMetadataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.invariantRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInvariantRule([NotNull] FSHParser.InvariantRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.invariantRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInvariantRule([NotNull] FSHParser.InvariantRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.valueSet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueSet([NotNull] FSHParser.ValueSetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.valueSet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueSet([NotNull] FSHParser.ValueSetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.vsMetadata"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVsMetadata([NotNull] FSHParser.VsMetadataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.vsMetadata"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVsMetadata([NotNull] FSHParser.VsMetadataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.vsRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVsRule([NotNull] FSHParser.VsRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.vsRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVsRule([NotNull] FSHParser.VsRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.codeSystem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCodeSystem([NotNull] FSHParser.CodeSystemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.codeSystem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCodeSystem([NotNull] FSHParser.CodeSystemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.csMetadata"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCsMetadata([NotNull] FSHParser.CsMetadataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.csMetadata"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCsMetadata([NotNull] FSHParser.CsMetadataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.csRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCsRule([NotNull] FSHParser.CsRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.csRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCsRule([NotNull] FSHParser.CsRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.ruleSet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRuleSet([NotNull] FSHParser.RuleSetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.ruleSet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRuleSet([NotNull] FSHParser.RuleSetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.ruleSetRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRuleSetRule([NotNull] FSHParser.RuleSetRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.ruleSetRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRuleSetRule([NotNull] FSHParser.RuleSetRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.ruleSetParamList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRuleSetParamList([NotNull] FSHParser.RuleSetParamListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.ruleSetParamList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRuleSetParamList([NotNull] FSHParser.RuleSetParamListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.ruleSetParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRuleSetParam([NotNull] FSHParser.RuleSetParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.ruleSetParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRuleSetParam([NotNull] FSHParser.RuleSetParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.ruleSetParamText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRuleSetParamText([NotNull] FSHParser.RuleSetParamTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.ruleSetParamText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRuleSetParamText([NotNull] FSHParser.RuleSetParamTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.ruleSetParamPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRuleSetParamPart([NotNull] FSHParser.RuleSetParamPartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.ruleSetParamPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRuleSetParamPart([NotNull] FSHParser.RuleSetParamPartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.paramRuleSetContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParamRuleSetContent([NotNull] FSHParser.ParamRuleSetContentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.paramRuleSetContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParamRuleSetContent([NotNull] FSHParser.ParamRuleSetContentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.mapping"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMapping([NotNull] FSHParser.MappingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.mapping"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMapping([NotNull] FSHParser.MappingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.mappingMetadata"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMappingMetadata([NotNull] FSHParser.MappingMetadataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.mappingMetadata"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMappingMetadata([NotNull] FSHParser.MappingMetadataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.mappingEntityRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMappingEntityRule([NotNull] FSHParser.MappingEntityRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.mappingEntityRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMappingEntityRule([NotNull] FSHParser.MappingEntityRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.parent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParent([NotNull] FSHParser.ParentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.parent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParent([NotNull] FSHParser.ParentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterId([NotNull] FSHParser.IdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitId([NotNull] FSHParser.IdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.title"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTitle([NotNull] FSHParser.TitleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.title"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTitle([NotNull] FSHParser.TitleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.description"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDescription([NotNull] FSHParser.DescriptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.description"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDescription([NotNull] FSHParser.DescriptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] FSHParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] FSHParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.xpath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterXpath([NotNull] FSHParser.XpathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.xpath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitXpath([NotNull] FSHParser.XpathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.severity"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSeverity([NotNull] FSHParser.SeverityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.severity"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSeverity([NotNull] FSHParser.SeverityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.instanceOf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstanceOf([NotNull] FSHParser.InstanceOfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.instanceOf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstanceOf([NotNull] FSHParser.InstanceOfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.usage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUsage([NotNull] FSHParser.UsageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.usage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUsage([NotNull] FSHParser.UsageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.source"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSource([NotNull] FSHParser.SourceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.source"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSource([NotNull] FSHParser.SourceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.target"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTarget([NotNull] FSHParser.TargetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.target"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTarget([NotNull] FSHParser.TargetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.context"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContext([NotNull] FSHParser.ContextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.context"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContext([NotNull] FSHParser.ContextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.contextItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContextItem([NotNull] FSHParser.ContextItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.contextItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContextItem([NotNull] FSHParser.ContextItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.characteristics"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCharacteristics([NotNull] FSHParser.CharacteristicsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.characteristics"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCharacteristics([NotNull] FSHParser.CharacteristicsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.cardRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCardRule([NotNull] FSHParser.CardRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.cardRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCardRule([NotNull] FSHParser.CardRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.flagRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFlagRule([NotNull] FSHParser.FlagRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.flagRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFlagRule([NotNull] FSHParser.FlagRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.valueSetRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueSetRule([NotNull] FSHParser.ValueSetRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.valueSetRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueSetRule([NotNull] FSHParser.ValueSetRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.fixedValueRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFixedValueRule([NotNull] FSHParser.FixedValueRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.fixedValueRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFixedValueRule([NotNull] FSHParser.FixedValueRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.containsRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContainsRule([NotNull] FSHParser.ContainsRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.containsRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContainsRule([NotNull] FSHParser.ContainsRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.onlyRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOnlyRule([NotNull] FSHParser.OnlyRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.onlyRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOnlyRule([NotNull] FSHParser.OnlyRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.obeysRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObeysRule([NotNull] FSHParser.ObeysRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.obeysRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObeysRule([NotNull] FSHParser.ObeysRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.caretValueRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaretValueRule([NotNull] FSHParser.CaretValueRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.caretValueRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaretValueRule([NotNull] FSHParser.CaretValueRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.codeCaretValueRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCodeCaretValueRule([NotNull] FSHParser.CodeCaretValueRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.codeCaretValueRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCodeCaretValueRule([NotNull] FSHParser.CodeCaretValueRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.mappingRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMappingRule([NotNull] FSHParser.MappingRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.mappingRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMappingRule([NotNull] FSHParser.MappingRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.insertRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInsertRule([NotNull] FSHParser.InsertRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.insertRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInsertRule([NotNull] FSHParser.InsertRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.ruleSetInsert"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRuleSetInsert([NotNull] FSHParser.RuleSetInsertContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.ruleSetInsert"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRuleSetInsert([NotNull] FSHParser.RuleSetInsertContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.codeInsertRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCodeInsertRule([NotNull] FSHParser.CodeInsertRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.codeInsertRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCodeInsertRule([NotNull] FSHParser.CodeInsertRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.addCRElementRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddCRElementRule([NotNull] FSHParser.AddCRElementRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.addCRElementRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddCRElementRule([NotNull] FSHParser.AddCRElementRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.addElementRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddElementRule([NotNull] FSHParser.AddElementRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.addElementRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddElementRule([NotNull] FSHParser.AddElementRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.pathRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPathRule([NotNull] FSHParser.PathRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.pathRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPathRule([NotNull] FSHParser.PathRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.vsComponent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVsComponent([NotNull] FSHParser.VsComponentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.vsComponent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVsComponent([NotNull] FSHParser.VsComponentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.vsConceptComponent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVsConceptComponent([NotNull] FSHParser.VsConceptComponentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.vsConceptComponent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVsConceptComponent([NotNull] FSHParser.VsConceptComponentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.vsFilterComponent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVsFilterComponent([NotNull] FSHParser.VsFilterComponentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.vsFilterComponent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVsFilterComponent([NotNull] FSHParser.VsFilterComponentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.vsComponentFrom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVsComponentFrom([NotNull] FSHParser.VsComponentFromContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.vsComponentFrom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVsComponentFrom([NotNull] FSHParser.VsComponentFromContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.vsFromSystem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVsFromSystem([NotNull] FSHParser.VsFromSystemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.vsFromSystem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVsFromSystem([NotNull] FSHParser.VsFromSystemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.vsFromValueset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVsFromValueset([NotNull] FSHParser.VsFromValuesetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.vsFromValueset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVsFromValueset([NotNull] FSHParser.VsFromValuesetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.vsFilterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVsFilterList([NotNull] FSHParser.VsFilterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.vsFilterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVsFilterList([NotNull] FSHParser.VsFilterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.vsFilterDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVsFilterDefinition([NotNull] FSHParser.VsFilterDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.vsFilterDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVsFilterDefinition([NotNull] FSHParser.VsFilterDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.vsFilterOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVsFilterOperator([NotNull] FSHParser.VsFilterOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.vsFilterOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVsFilterOperator([NotNull] FSHParser.VsFilterOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.vsFilterValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVsFilterValue([NotNull] FSHParser.VsFilterValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.vsFilterValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVsFilterValue([NotNull] FSHParser.VsFilterValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterName([NotNull] FSHParser.NameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitName([NotNull] FSHParser.NameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.path"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPath([NotNull] FSHParser.PathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.path"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPath([NotNull] FSHParser.PathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.caretPath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaretPath([NotNull] FSHParser.CaretPathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.caretPath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaretPath([NotNull] FSHParser.CaretPathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.flag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFlag([NotNull] FSHParser.FlagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.flag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFlag([NotNull] FSHParser.FlagContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.strength"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStrength([NotNull] FSHParser.StrengthContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.strength"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStrength([NotNull] FSHParser.StrengthContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] FSHParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] FSHParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterItem([NotNull] FSHParser.ItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitItem([NotNull] FSHParser.ItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.code"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCode([NotNull] FSHParser.CodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.code"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCode([NotNull] FSHParser.CodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.concept"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConcept([NotNull] FSHParser.ConceptContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.concept"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConcept([NotNull] FSHParser.ConceptContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.quantity"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuantity([NotNull] FSHParser.QuantityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.quantity"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuantity([NotNull] FSHParser.QuantityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.ratio"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRatio([NotNull] FSHParser.RatioContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.ratio"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRatio([NotNull] FSHParser.RatioContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReference([NotNull] FSHParser.ReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReference([NotNull] FSHParser.ReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.referenceType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReferenceType([NotNull] FSHParser.ReferenceTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.referenceType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReferenceType([NotNull] FSHParser.ReferenceTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.codeableReferenceType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCodeableReferenceType([NotNull] FSHParser.CodeableReferenceTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.codeableReferenceType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCodeableReferenceType([NotNull] FSHParser.CodeableReferenceTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.canonical"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCanonical([NotNull] FSHParser.CanonicalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.canonical"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCanonical([NotNull] FSHParser.CanonicalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.ratioPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRatioPart([NotNull] FSHParser.RatioPartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.ratioPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRatioPart([NotNull] FSHParser.RatioPartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool([NotNull] FSHParser.BoolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool([NotNull] FSHParser.BoolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.targetType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTargetType([NotNull] FSHParser.TargetTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.targetType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTargetType([NotNull] FSHParser.TargetTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.mostAlphaKeywords"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMostAlphaKeywords([NotNull] FSHParser.MostAlphaKeywordsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.mostAlphaKeywords"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMostAlphaKeywords([NotNull] FSHParser.MostAlphaKeywordsContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace fsh_processor.antlr
