//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from fsh-processor/antlr/FSH.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace fsh_processor.antlr {
// Disable the warning for CLSCompliant
#pragma warning disable 3021

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="FSHParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IFSHListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.doc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoc([NotNull] FSHParser.DocContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.doc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoc([NotNull] FSHParser.DocContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.entity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEntity([NotNull] FSHParser.EntityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.entity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEntity([NotNull] FSHParser.EntityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlias([NotNull] FSHParser.AliasContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlias([NotNull] FSHParser.AliasContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.profile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProfile([NotNull] FSHParser.ProfileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.profile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProfile([NotNull] FSHParser.ProfileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.extension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtension([NotNull] FSHParser.ExtensionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.extension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtension([NotNull] FSHParser.ExtensionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.logical"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogical([NotNull] FSHParser.LogicalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.logical"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogical([NotNull] FSHParser.LogicalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.resource"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterResource([NotNull] FSHParser.ResourceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.resource"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitResource([NotNull] FSHParser.ResourceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.sdMetadata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSdMetadata([NotNull] FSHParser.SdMetadataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.sdMetadata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSdMetadata([NotNull] FSHParser.SdMetadataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.sdRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSdRule([NotNull] FSHParser.SdRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.sdRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSdRule([NotNull] FSHParser.SdRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.lrRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLrRule([NotNull] FSHParser.LrRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.lrRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLrRule([NotNull] FSHParser.LrRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.instance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstance([NotNull] FSHParser.InstanceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.instance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstance([NotNull] FSHParser.InstanceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.instanceMetadata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstanceMetadata([NotNull] FSHParser.InstanceMetadataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.instanceMetadata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstanceMetadata([NotNull] FSHParser.InstanceMetadataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.instanceRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstanceRule([NotNull] FSHParser.InstanceRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.instanceRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstanceRule([NotNull] FSHParser.InstanceRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.invariant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInvariant([NotNull] FSHParser.InvariantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.invariant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInvariant([NotNull] FSHParser.InvariantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.invariantMetadata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInvariantMetadata([NotNull] FSHParser.InvariantMetadataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.invariantMetadata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInvariantMetadata([NotNull] FSHParser.InvariantMetadataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.invariantRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInvariantRule([NotNull] FSHParser.InvariantRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.invariantRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInvariantRule([NotNull] FSHParser.InvariantRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.valueSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueSet([NotNull] FSHParser.ValueSetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.valueSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueSet([NotNull] FSHParser.ValueSetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.vsMetadata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsMetadata([NotNull] FSHParser.VsMetadataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.vsMetadata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsMetadata([NotNull] FSHParser.VsMetadataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.vsRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsRule([NotNull] FSHParser.VsRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.vsRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsRule([NotNull] FSHParser.VsRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.codeSystem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodeSystem([NotNull] FSHParser.CodeSystemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.codeSystem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodeSystem([NotNull] FSHParser.CodeSystemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.csMetadata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCsMetadata([NotNull] FSHParser.CsMetadataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.csMetadata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCsMetadata([NotNull] FSHParser.CsMetadataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.csRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCsRule([NotNull] FSHParser.CsRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.csRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCsRule([NotNull] FSHParser.CsRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.ruleSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRuleSet([NotNull] FSHParser.RuleSetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.ruleSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRuleSet([NotNull] FSHParser.RuleSetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.ruleSetRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRuleSetRule([NotNull] FSHParser.RuleSetRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.ruleSetRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRuleSetRule([NotNull] FSHParser.RuleSetRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.ruleSetParamList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRuleSetParamList([NotNull] FSHParser.RuleSetParamListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.ruleSetParamList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRuleSetParamList([NotNull] FSHParser.RuleSetParamListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.ruleSetParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRuleSetParam([NotNull] FSHParser.RuleSetParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.ruleSetParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRuleSetParam([NotNull] FSHParser.RuleSetParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.ruleSetParamText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRuleSetParamText([NotNull] FSHParser.RuleSetParamTextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.ruleSetParamText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRuleSetParamText([NotNull] FSHParser.RuleSetParamTextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.ruleSetParamPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRuleSetParamPart([NotNull] FSHParser.RuleSetParamPartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.ruleSetParamPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRuleSetParamPart([NotNull] FSHParser.RuleSetParamPartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.paramRuleSetContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamRuleSetContent([NotNull] FSHParser.ParamRuleSetContentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.paramRuleSetContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamRuleSetContent([NotNull] FSHParser.ParamRuleSetContentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.mapping"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMapping([NotNull] FSHParser.MappingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.mapping"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMapping([NotNull] FSHParser.MappingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.mappingMetadata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMappingMetadata([NotNull] FSHParser.MappingMetadataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.mappingMetadata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMappingMetadata([NotNull] FSHParser.MappingMetadataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.mappingEntityRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMappingEntityRule([NotNull] FSHParser.MappingEntityRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.mappingEntityRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMappingEntityRule([NotNull] FSHParser.MappingEntityRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.parent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParent([NotNull] FSHParser.ParentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.parent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParent([NotNull] FSHParser.ParentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterId([NotNull] FSHParser.IdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitId([NotNull] FSHParser.IdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.title"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTitle([NotNull] FSHParser.TitleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.title"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTitle([NotNull] FSHParser.TitleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.description"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDescription([NotNull] FSHParser.DescriptionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.description"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDescription([NotNull] FSHParser.DescriptionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] FSHParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] FSHParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.xpath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterXpath([NotNull] FSHParser.XpathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.xpath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitXpath([NotNull] FSHParser.XpathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.severity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSeverity([NotNull] FSHParser.SeverityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.severity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSeverity([NotNull] FSHParser.SeverityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.instanceOf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstanceOf([NotNull] FSHParser.InstanceOfContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.instanceOf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstanceOf([NotNull] FSHParser.InstanceOfContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.usage"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUsage([NotNull] FSHParser.UsageContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.usage"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUsage([NotNull] FSHParser.UsageContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.source"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSource([NotNull] FSHParser.SourceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.source"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSource([NotNull] FSHParser.SourceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTarget([NotNull] FSHParser.TargetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTarget([NotNull] FSHParser.TargetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.context"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContext([NotNull] FSHParser.ContextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.context"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContext([NotNull] FSHParser.ContextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.contextItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContextItem([NotNull] FSHParser.ContextItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.contextItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContextItem([NotNull] FSHParser.ContextItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.characteristics"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCharacteristics([NotNull] FSHParser.CharacteristicsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.characteristics"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCharacteristics([NotNull] FSHParser.CharacteristicsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.cardRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCardRule([NotNull] FSHParser.CardRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.cardRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCardRule([NotNull] FSHParser.CardRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.flagRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFlagRule([NotNull] FSHParser.FlagRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.flagRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFlagRule([NotNull] FSHParser.FlagRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.valueSetRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueSetRule([NotNull] FSHParser.ValueSetRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.valueSetRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueSetRule([NotNull] FSHParser.ValueSetRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.fixedValueRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFixedValueRule([NotNull] FSHParser.FixedValueRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.fixedValueRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFixedValueRule([NotNull] FSHParser.FixedValueRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.containsRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContainsRule([NotNull] FSHParser.ContainsRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.containsRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContainsRule([NotNull] FSHParser.ContainsRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.onlyRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOnlyRule([NotNull] FSHParser.OnlyRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.onlyRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOnlyRule([NotNull] FSHParser.OnlyRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.obeysRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObeysRule([NotNull] FSHParser.ObeysRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.obeysRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObeysRule([NotNull] FSHParser.ObeysRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.caretValueRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaretValueRule([NotNull] FSHParser.CaretValueRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.caretValueRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaretValueRule([NotNull] FSHParser.CaretValueRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.codeCaretValueRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodeCaretValueRule([NotNull] FSHParser.CodeCaretValueRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.codeCaretValueRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodeCaretValueRule([NotNull] FSHParser.CodeCaretValueRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.mappingRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMappingRule([NotNull] FSHParser.MappingRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.mappingRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMappingRule([NotNull] FSHParser.MappingRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.insertRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInsertRule([NotNull] FSHParser.InsertRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.insertRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInsertRule([NotNull] FSHParser.InsertRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.ruleSetInsert"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRuleSetInsert([NotNull] FSHParser.RuleSetInsertContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.ruleSetInsert"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRuleSetInsert([NotNull] FSHParser.RuleSetInsertContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.codeInsertRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodeInsertRule([NotNull] FSHParser.CodeInsertRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.codeInsertRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodeInsertRule([NotNull] FSHParser.CodeInsertRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.addCRElementRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddCRElementRule([NotNull] FSHParser.AddCRElementRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.addCRElementRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddCRElementRule([NotNull] FSHParser.AddCRElementRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.addElementRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddElementRule([NotNull] FSHParser.AddElementRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.addElementRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddElementRule([NotNull] FSHParser.AddElementRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.pathRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPathRule([NotNull] FSHParser.PathRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.pathRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPathRule([NotNull] FSHParser.PathRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.vsComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsComponent([NotNull] FSHParser.VsComponentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.vsComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsComponent([NotNull] FSHParser.VsComponentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.vsConceptComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsConceptComponent([NotNull] FSHParser.VsConceptComponentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.vsConceptComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsConceptComponent([NotNull] FSHParser.VsConceptComponentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.vsFilterComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsFilterComponent([NotNull] FSHParser.VsFilterComponentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.vsFilterComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsFilterComponent([NotNull] FSHParser.VsFilterComponentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.vsComponentFrom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsComponentFrom([NotNull] FSHParser.VsComponentFromContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.vsComponentFrom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsComponentFrom([NotNull] FSHParser.VsComponentFromContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.vsFromSystem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsFromSystem([NotNull] FSHParser.VsFromSystemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.vsFromSystem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsFromSystem([NotNull] FSHParser.VsFromSystemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.vsFromValueset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsFromValueset([NotNull] FSHParser.VsFromValuesetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.vsFromValueset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsFromValueset([NotNull] FSHParser.VsFromValuesetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.vsFilterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsFilterList([NotNull] FSHParser.VsFilterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.vsFilterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsFilterList([NotNull] FSHParser.VsFilterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.vsFilterDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsFilterDefinition([NotNull] FSHParser.VsFilterDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.vsFilterDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsFilterDefinition([NotNull] FSHParser.VsFilterDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.vsFilterOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsFilterOperator([NotNull] FSHParser.VsFilterOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.vsFilterOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsFilterOperator([NotNull] FSHParser.VsFilterOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.vsFilterValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsFilterValue([NotNull] FSHParser.VsFilterValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.vsFilterValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsFilterValue([NotNull] FSHParser.VsFilterValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterName([NotNull] FSHParser.NameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitName([NotNull] FSHParser.NameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPath([NotNull] FSHParser.PathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPath([NotNull] FSHParser.PathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.caretPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaretPath([NotNull] FSHParser.CaretPathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.caretPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaretPath([NotNull] FSHParser.CaretPathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.flag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFlag([NotNull] FSHParser.FlagContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.flag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFlag([NotNull] FSHParser.FlagContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.strength"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStrength([NotNull] FSHParser.StrengthContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.strength"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStrength([NotNull] FSHParser.StrengthContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] FSHParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] FSHParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterItem([NotNull] FSHParser.ItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitItem([NotNull] FSHParser.ItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.code"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCode([NotNull] FSHParser.CodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.code"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCode([NotNull] FSHParser.CodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.concept"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConcept([NotNull] FSHParser.ConceptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.concept"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConcept([NotNull] FSHParser.ConceptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.quantity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuantity([NotNull] FSHParser.QuantityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.quantity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuantity([NotNull] FSHParser.QuantityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.ratio"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRatio([NotNull] FSHParser.RatioContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.ratio"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRatio([NotNull] FSHParser.RatioContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReference([NotNull] FSHParser.ReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReference([NotNull] FSHParser.ReferenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.referenceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReferenceType([NotNull] FSHParser.ReferenceTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.referenceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReferenceType([NotNull] FSHParser.ReferenceTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.codeableReferenceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodeableReferenceType([NotNull] FSHParser.CodeableReferenceTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.codeableReferenceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodeableReferenceType([NotNull] FSHParser.CodeableReferenceTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.canonical"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCanonical([NotNull] FSHParser.CanonicalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.canonical"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCanonical([NotNull] FSHParser.CanonicalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.ratioPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRatioPart([NotNull] FSHParser.RatioPartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.ratioPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRatioPart([NotNull] FSHParser.RatioPartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBool([NotNull] FSHParser.BoolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBool([NotNull] FSHParser.BoolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.targetType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTargetType([NotNull] FSHParser.TargetTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.targetType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTargetType([NotNull] FSHParser.TargetTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FSHParser.mostAlphaKeywords"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMostAlphaKeywords([NotNull] FSHParser.MostAlphaKeywordsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FSHParser.mostAlphaKeywords"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMostAlphaKeywords([NotNull] FSHParser.MostAlphaKeywordsContext context);
}
} // namespace fsh_processor.antlr
