<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Hl7.FhirShorthand.Compiler</RootNamespace>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hl7.Fhir.Conformance" Version="5.13.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\fsh-processor\Hl7.FhirShorthand.Serialization.csproj" />
  </ItemGroup>

</Project>
